# Generated by Django 5.2.10 on 2026-02-20 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0004_workerpayoutdetails'),
        ('notification', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='chat_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Worker.chatrequest'),
        ),
    ]
