# Generated by Django 5.2.10 on 2026-03-06 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0001_initial'),
        ('orders', '0007_order_components_total_order_platform_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerearning',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_earning_record', to='orders.order'),
        ),
    ]
