# Generated by Django 5.2.10 on 2026-02-16 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0002_chatrequest_chatroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerIdentityKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN'), ('dl', 'Driving License'), ('voter', 'Voter ID')], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('id_front_url', models.URLField()),
                ('id_front_id', models.CharField(max_length=255)),
                ('id_back_url', models.URLField(blank=True, null=True)),
                ('id_back_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
