# Generated by Django 5.2.10 on 2026-01-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_user_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
