# Generated by Django 5.2.10 on 2026-01-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='profile_image_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
