# Generated by Django 5.2.10 on 2026-02-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_userprofile_profile_image_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerprofile',
            old_name='status',
            new_name='kyc_status',
        ),
    ]
