# Generated by Django 5.2.10 on 2026-02-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_rename_status_workerprofile_kyc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='banner_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='banner_image_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
