# Generated by Django 5.2.10 on 2026-02-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_workerprofile_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='kyc_status',
            field=models.CharField(choices=[('started', 'Started'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='started', max_length=20),
        ),
    ]
