# Generated by Django 5.2.10 on 2026-02-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quotation_pdf',
            field=models.FileField(blank=True, null=True, upload_to='quotations/'),
        ),
    ]
