# Generated by Django 5.2.10 on 2026-02-20 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('model_number', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='MotherboardSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(max_length=50)),
                ('chipset', models.CharField(max_length=50)),
                ('ram_type', models.CharField(max_length=20)),
                ('max_ram_gb', models.PositiveIntegerField()),
                ('ram_slots', models.PositiveIntegerField()),
                ('form_factor', models.CharField(max_length=20)),
                ('pcie_version', models.CharField(blank=True, max_length=10, null=True)),
                ('m2_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('sata_ports', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard_spec', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='GPUSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_gb', models.PositiveIntegerField()),
                ('memory_type', models.CharField(max_length=20)),
                ('base_clock_mhz', models.PositiveIntegerField()),
                ('boost_clock_mhz', models.PositiveIntegerField(blank=True, null=True)),
                ('length_mm', models.PositiveIntegerField(help_text='GPU length in mm')),
                ('tdp', models.PositiveIntegerField(help_text='TDP in watts')),
                ('recommended_psu_watt', models.PositiveIntegerField(blank=True, null=True)),
                ('gpu_chipset', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_spec', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='CPUSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(max_length=50)),
                ('cores', models.PositiveIntegerField()),
                ('threads', models.PositiveIntegerField()),
                ('base_clock', models.DecimalField(decimal_places=2, max_digits=5)),
                ('boost_clock', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tdp', models.PositiveIntegerField(help_text='TDP in watts')),
                ('has_integrated_graphics', models.BooleanField(default=False)),
                ('series', models.CharField(blank=True, max_length=50, null=True)),
                ('l3_cache', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_spec', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='COOLERSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooler_type', models.CharField(max_length=50)),
                ('supported_sockets', models.CharField(max_length=100)),
                ('cooler_height_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('fan_size', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cooler_spec', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='CASESpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supported_form_factors', models.CharField(max_length=100)),
                ('max_gpu_length_mm', models.PositiveIntegerField()),
                ('max_cpu_cooler_height_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('has_rgb', models.BooleanField(default=False)),
                ('side_panel', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_spec', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='CASEFANSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_size', models.CharField(max_length=20)),
                ('rpm', models.PositiveIntegerField()),
                ('has_rgb', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='casefan_spec', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='PSUSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wattage', models.PositiveIntegerField(help_text='Wattage in watts')),
                ('modular_type', models.CharField(max_length=100)),
                ('efficiency_rating', models.CharField(max_length=20)),
                ('form_factor', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psu_spec', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='RAMSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_type', models.CharField(max_length=20)),
                ('capacity_gb', models.PositiveIntegerField()),
                ('frequency_mhz', models.PositiveIntegerField()),
                ('stick_count', models.PositiveIntegerField(default=1)),
                ('voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ram_spec', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='STORAGESpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(max_length=20)),
                ('interface', models.CharField(max_length=20)),
                ('capacity_gb', models.PositiveIntegerField()),
                ('read_speed', models.PositiveIntegerField(help_text='MB/s')),
                ('write_speed', models.PositiveIntegerField(help_text='MB/s')),
                ('form_factor', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_spec', to='products.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='products_pr_brand_i_dc6890_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_deleted'], name='products_pr_is_acti_269a72_idx'),
        ),
    ]
