# Generated by Django 5.2.10 on 2026-02-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casespec',
            name='supported_fan_sizes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
